runtime: nodejs18
env: standard
instance_class: F2
handlers:
  - url: .*
    script: auto
  - url: .*
    script: auto
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
service_account: expoactiva-movilapp@appspot.gserviceaccount.com