version: '3'
services:
  web:
    build: .
    environment:
      - MONGODB_URI=mongodb+srv://lazaroborghi:Lb2023$21@clusterexpoactiva.bwdb9x0.mongodb.net/
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
