name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancelar builds redundantes anteriores
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18'
          cache: 'npm'

      - name: 1- Instalar dependencias
        run: npm install --no-audit --no-fund --no-optional

      # Correr linter para verificar errores en el código (por ahora no hay)

      # Correr tests
      - name: 2- Correr tests
        run: npm test

      # Instalar el SDK de Google Cloud
      - name: 3- Instalar Google Cloud SDK
        run: |
          sudo apt-get update
          sudo apt-get install google-cloud-sdk
    
      # Establecer proyecto de Google Cloud
      - name: 4- Establecer proyecto de Google Cloud
        run: |
          gcloud config set project expoactiva-nacional-395522

      # Despliegue a Google App Engine
      - name: 5- Despliegue a Google App Engine
        if: success()
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "$GCP_CREDENTIALS" | gcloud auth activate-service-account --key-file=-
          gcloud app deploy
