name: Prod CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  
  avoid_redundant_builds:
    runs-on: ubuntu-20.04
    steps:
    - name: Cancelar builds redundantes anteriores
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    needs: avoid_redundant_builds
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'npm'
    - name: Instalar dependencias
      run: npm install --no-audit --no-fund --no-optional
    - name: Correr linter
      run: npm run lint

  test:
    needs: [avoid_redundant_builds, lint]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'npm'
    - name: Instalar dependencias
      run: npm install --no-audit --no-fund --no-optional
    - name: Correr tests
      run: npm test

  deploy:
    needs: [lint, test]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Instalar Google Cloud SDK
      run: sudo apt-get update && sudo apt-get install google-cloud-sdk
    - name: Establecer proyecto de Google Cloud
      run: gcloud config set project expoactiva-nacional-395522
    - name: Despliegue a Google App Engine
      if: ${{ github.event_name == 'push' }}
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      run: |
        echo "$GCP_CREDENTIALS" | gcloud auth activate-service-account --key-file=-
        gcloud app deploy
