name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'

    # Caching dependencies
    - name: Cache de dependencias
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-

    - name: Instalar dependencias
      run: npm install

    # Correr linter para verificar errores en el código (por ahora no hay)

    - name: Correr tests
      run: npm test

    # Instalar el SDK de Google Cloud
    - name: Instalar Google Cloud SDK
      run: |
        sudo apt-get update
        sudo apt-get install google-cloud-sdk
    
    # Establecer proyecto de Google Cloud
    - name: Establecer proyecto de Google Cloud
      run: |
        gcloud config set project expoactiva-nacional-395522

    # Despliegue a Google App Engine
    - name: Despliegue a Google App Engine
      if: success()
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      run: |
        echo "$GCP_CREDENTIALS" | gcloud auth activate-service-account --key-file=-
        gcloud app deploy
