name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: Instalar dependencias
      run: npm install

    - name: Correr tests
      run: npm test

    # Instalar el SDK de Google Cloud
    - name: Instalar Google Cloud SDK
      run: |
        sudo apt-get update
        sudo apt-get install google-cloud-sdk
    
    # Establecer proyecto de Google Cloud
    - name: Establecer proyecto de Google Cloud
      run: |
        gcloud config set project expoactiva-nacional-395522

    # Despliegue a Google App Engine
    # Solo si los tests pasan, hace el despliegue.
    - name: Despliegue a Google App Engine
      if: success()
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      run: |
        echo "$GCP_CREDENTIALS" | gcloud auth activate-service-account --key-file=-
        gcloud app deploy
