name: Prod CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  avoid_redundant_builds:
    runs-on: ubuntu-20.04
    steps:
    - name: Cancelar builds redundantes anteriores
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    needs: avoid_redundant_builds
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Instalar dependencias
      run: bun install

    - name: Correr linter
      run: npm run lint

  test:
    needs: avoid_redundant_builds
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Instalar dependencias
      run: bun install
      
    - name: Correr tests
      run: npm test

  deploy:
    needs: [lint, test]
    runs-on: ubuntu-20.04

    container:
      image: google/cloud-sdk:alpine

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Establecer proyecto de Google Cloud
      run: gcloud config set project expoactiva-nacional-395522

    - name: Autenticación con Google Cloud
      run: |
        echo "$GCP_CREDENTIALS" > key.json
        gcloud auth activate-service-account --key-file=key.json
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
    
    - name: Despliegue a Google App Engine
      if: ${{ github.event_name == 'push' }}
      run: gcloud app deploy
