name: Rollback automatico

on:
  workflow_dispatch: # permite ejecuciones manuales

jobs:
  rollback:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Google Cloud SDK
      run: |
        sudo apt-get update
        sudo apt-get install google-cloud-sdk

    - name: Autenticar GCP
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      run: |
        echo "$GCP_CREDENTIALS" | gcloud auth activate-service-account --key-file=-

    - name: Establece proyecto de GCP
      run: |
        gcloud config set project expoactiva-nacional-395522

    - name: Obtiene la ultima version desplegada
      id: last-version
      run: |
        LAST_VERSION=$(gcloud app versions list --sort-by '~version.id' --limit 1 --format 'value(version.id)')
        echo "Last deployed version is $LAST_VERSION"
        echo "::set-output name=version::$LAST_VERSION"

    - name: Inicia rollback
      run: |
        gcloud app versions start ${{ steps.last-version.outputs.version }}
