name: Rollback automático

on:
  workflow_dispatch: # permite ejecuciones manuales

jobs:
  rollback:
    runs-on: ubuntu-20.04
    container:
      image: google/cloud-sdk:alpine

    steps:

    - uses: actions/checkout@v3
    - name: Establecer proyecto de Google Cloud
      run: gcloud config set project expoactiva-nacional-395522

    - name: Autenticación con Google Cloud
      run: |
        echo "$GCP_CREDENTIALS" > key.json
        gcloud auth activate-service-account --key-file=key.json
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

    - name: Establece proyecto de GCP
      run: |
        gcloud config set project expoactiva-nacional-395522

    - name: Obtiene la segunda última versión desplegada
      run: |
        SECOND_LAST_VERSION=$(gcloud app versions list --sort-by '~version.id' --limit 2 --format 'value(version.id)' | tail -n1)
        echo "Second last deployed version is $SECOND_LAST_VERSION"
        echo "SECOND_LAST_VERSION=$SECOND_LAST_VERSION" >> $GITHUB_ENV

    - name: Redirige todo el tráfico a la segunda última versión
      run: |
        gcloud app services set-traffic default --splits $SECOND_LAST_VERSION=1
